# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tag
    value: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildImage
        displayName: Build Image
        steps:
          - script: ls /home/vsts/work/1/s/
            displayName: ls 1
          
          - script: ls /home/vsts/work/1/s/medjoin
            displayName: ls 2
          - task: Docker@2
            inputs:
              containerRegistry: 'acrmedjoin'
              repository: 'medjoin'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(tag)