# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tag
    value: '$(Build.BuildId)'

resources:
  pipelines:
    - pipeline: medjoiniaac
      source: medjoin-iaac

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildImage
        displayName: Build Image
        steps:
          # - download: medjoiniaac
          
          

          # - task: Docker@2
          #   inputs:
          #     containerRegistry: 'acrmedjoin'
          #     repository: 'medjoin'
          #     command: 'buildAndPush'
          #     Dockerfile: '**/Dockerfile'
          #     tags: $(tag)
          - script: cat $(Build.SourcesDirectory)/medjoin/manifest/deployment.yml
            displayName: cat 1

          - task: CmdLine@2
            displayName: 'Build manifests'
            inputs:
              script: 'sed "s/(tag)/"$(tag)"/" $(Build.SourcesDirectory)/medjoin/manifest/deployment.yml > $(Build.SourcesDirectory)/medjoin/manifest/deployment.yml'

          - script: ls $(Build.SourcesDirectory)/medjoin/manifest
            displayName: ls

          - script: cat $(Build.SourcesDirectory)/medjoin/manifest/deployment.yml
            displayName: cat 2

          - publish: $(Build.SourcesDirectory)/medjoin/manifest
            artifact: manifest
            displayName: Publish Manifest

